# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QaplDmPbhBx9_DT8ikS1zAaqbQb8_-LJ
"""

ARCHES = ["baseline", "zsplit_sem", "zsplit_robust", "zsplit_gate"]

for arch in ARCHES:
    print("=" * 80)
    print(f"Training architecture: {arch} (80 epochs)")
    print("Start")
    print("=" * 80)

    # PYTHONUNBUFFERED=1, -u 옵션으로 버퍼링 최소화해서 tqdm가 바로바로 뜨게 함
    !PYTHONUNBUFFERED=1 python -u main.py \
        --arch {arch} \
        --epochs 80 \
        --channel Rician \
        --checkpoint-path checkpoints/{arch}_80epoch